spring:
#  config:
#    import: config-server:http://config-server:8088
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    url: jdbc:h2:mem:keynotedb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/conference-realm
          jwk-set-uri: http://localhost:8080/realms/conference-realm/protocol/openid-connect/certs
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info # Endpoints to expose
  endpoint:
    refresh:
      enabled: true
    health:
      show-details: always
